name = "RefinedSlippage"
uuid = "f102acab-2a34-462b-8f40-530debd6834f"
authors = ["Stuart Baumann <13663771+s-baumann@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HighFrequencyCovariance = "c79ce38c-73ba-4c3d-834c-fb94999fb590"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"

[compat]
DataFrames = "1.8.1"
Dates = "1.11.0"
HighFrequencyCovariance = "0.5.2"
LinearAlgebra = "1.11.0"
Random = "1.11.0"
StableRNGs = "1.0.4"
TimeZones = "1.22.2"
VegaLite = "3.3.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
